FROM docker.io/kalilinux/kali-rolling

LABEL org.opencontainers.image.source="https://github.com/qubesome/workload-images" \
      org.opencontainers.image.ref.name="kali" \
      org.opencontainers.image.title="qubesome Kali workload" \
      org.opencontainers.image.description="Kali linux for qubesome."
