#!/usr/bin/env bash

set -euo pipefail

if [ "$#" -ne 2 ]; then
    echo "usage: $0 /tmp/target-file $UID (target user ID)"
    exit 0
fi

ROOT_PASS="${ROOT_PASS:-root}"
TARGET_FILE=$1
UID=$2
MOUNT_PATH=$(mktemp -d)

dd if=/dev/zero of="${TARGET_FILE}" bs=1M count=500
mkfs.ext4 "${TARGET_FILE}"

mount "${TARGET_FILE}" "${MOUNT_PATH}"

# Then, copy the newly configured system to the rootfs image:
for d in boot bin etc lib root sbin usr; do tar c "/$d" | tar x -C "${MOUNT_PATH}"; done

# The above command may trigger the following message:
# tar: Removing leading "/" from member names
# However, this is just a warning, so you should be able to
# proceed with the setup process.
for dir in dev proc run sys var/run var/tmp var/log; do mkdir -p "${MOUNT_PATH}/${dir}"; done

echo "root:${ROOT_PASS}" | chpasswd
cp /etc/shadow "${MOUNT_PATH}/etc"

umount "${MOUNT_PATH}"
rm -rf "${MOUNT_PATH}"

chown "${UID}" "${TARGET_FILE}"

exit 0
