#!/bin/bash

set -xeo pipefail

IMAGE="${IMAGE:-ghcr.io/qubesome/code-golang:latest}"
#PROFILE=${PROFILE:-work}
PROFILE=work
CONTAINER_NAME="code-golang-${PROFILE}"
HOMEDIR="${HOME}/.qubesome/profiles/${PROFILE}/homedir"

if [ -z "$(docker ps -a -q -f name=${CONTAINER_NAME})" ]; then
    docker run --rm -d \
        -v /etc/localtime:/etc/localtime:ro \
        -v /etc/machine-id:/etc/machine-id:ro \
        -v "${HOMEDIR}/.gitconfig:/home/coder/.gitconfig:ro" \
        -v "${HOMEDIR}/.gitconfig-work:/home/coder/.gitconfig-work:ro" \
        -v "${HOMEDIR}/.gitignore:/home/coder/.gitignore:ro" \
        -v ~/.oh-my-zsh:/home/coder/.oh-my-zsh:ro \
        -v ~/.zshrc:/home/coder/.zshrc:ro \
        --network none \
        --security-opt seccomp=unconfined \
        --device /dev/dri:/dev/dri -v /dev/shm:/dev/shm \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v /run/dbus/system_bus_socket:/run/dbus/system_bus_socket \
        -v /run/user/1000/bus:/run/user/1000/bus \
        -v /var/lib/dbus:/var/lib/dbus -v /run/user/1000/dbus-1:/run/user/1000/dbus-1 \
        -e DISPLAY -e DBUS_SESSION_BUS_ADDRESS -e XDG_RUNTIME_DIR \
        -e XDG_SESSION_ID \
        -v ~/git:/home/coder/git \
        -v ~/go:/home/coder/go \
        -v "${HOMEDIR}/.config/Code:/home/coder/.config/Code" \
        -v /run/user/1000:/run/user/1000 \
        --name "${CONTAINER_NAME}" \
        "${IMAGE}" \
        code --disable-gpu --verbose "$1"
else
    docker exec "${CONTAINER_NAME}" code "$1"
fi
