#!/bin/bash

set -xeo pipefail

IMAGE="${IMAGE:-ghcr.io/qubesome/chrome:latest}"
PROFILE=${PROFILE:-personal}
CONTAINER_NAME="chrome-${PROFILE}"
HOMEDIR="${HOME}/.qubesome/profiles/${PROFILE}/homedir"

SMART_CARD_NAME=YubiKey
CAMERA_NAME="Logitech USB Receiver"

sc_devs=$(grep -R "${SMART_CARD_NAME}" /sys/class/hidraw/*/device/uevent | cut -d'/' -f 5 | xargs -I{} echo -n "--device /dev/{} ")
camera_devs=$(grep -R "${CAMERA_NAME}" /sys/class/hidraw/*/device/uevent | cut -d'/' -f 5 | xargs -I{} echo -n "--device /dev/{} ")

if [ -z "$(docker ps -a -q -f name=${CONTAINER_NAME})" ]; then
    docker run --rm -d \
        -v /etc/localtime:/etc/localtime:ro \
        -v /etc/machine-id:/etc/machine-id:ro \
        --security-opt seccomp=unconfined \
        --device /dev/dri:/dev/dri \
        -v /dev:/dev \
        -v /dev/shm:/dev/shm \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v /run/dbus/system_bus_socket:/run/dbus/system_bus_socket -v /run/user/1000/bus:/run/user/1000/bus \
        -v /var/lib/dbus:/var/lib/dbus -v /run/user/1000/dbus-1:/run/user/1000/dbus-1 \
        -e DISPLAY -e DBUS_SESSION_BUS_ADDRESS \
        -e XDG_RUNTIME_DIR -e XDG_SESSION_ID \
        -v /run/user/1000/pipewire-0:/run/user/1000/pipewire-0 \
        --device /dev/snd --group-add audio \
        ${camera_devs} \
        ${sc_devs} \
        --device=/dev/video0 \
        --group-add video --name chrome \
    	-v "${HOMEDIR}/Downloads:/home/chrome/Downloads" \
	    -v "${HOMEDIR}/.config/google-chrome:/home/chrome/.config/google-chrome" \
        --name "${CONTAINER_NAME}" \
        "${IMAGE}" /usr/bin/google-chrome "$1"
else
    docker exec "${CONTAINER_NAME}" /usr/bin/google-chrome "$1"
fi
