---
name: Slack bump

permissions:
  pull-requests: write
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 2'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Patch Slack Dockerfile
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Slack patcher"

          ./hack/patch-slack.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
