name: test

on:
  push:

permissions:
  contents: read

env: 
  REPO: ghcr.io/${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: cosign-installer
        uses: sigstore/cosign-installer@v3
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - run: make build
